import SignalFeed from '@/components/SignalFeed'
import type { Signal } from '@/lib/types'

async function fetchSignals(): Promise<Signal[]> {
  try {
    const base = process.env.NEXT_PUBLIC_BASE_URL ?? 'http://localhost:3000'
    const res = await fetch(`${base}/api/signals?limit=20`, { cache: 'no-store' })
    if (!res.ok) return []
    return res.json() as Promise<Signal[]>
  } catch {
    return []
  }
}

export default async function SignalsPage() {
  const signals = await fetchSignals()

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-100">Live signals</h1>
        <p className="text-sm text-gray-500 mt-1">
          Real-time BUY / SELL signals generated by the XGBoost model
        </p>
      </div>
      <SignalFeed initialSignals={signals} />
    </div>
  )
}
